version: '3'
services:
  database:
    container_name: ${PROJECT_NAME}_database
    restart: on-failure
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: app_db
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/app/public
    networks:
      - app-network

  php:
    container_name: ${PROJECT_NAME}_php
    build: ./php
    volumes:
      - ./app:/var/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: