FROM php:8.2-fpm

WORKDIR /var/app

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN apt-get update && apt-get install -y \
    zlib1g-dev \
    libzip-dev \
    unzip \
    git

RUN docker-php-ext-install zip
RUN docker-php-ext-install mysqli pdo pdo_mysql
